### ISSUE TITLE
Display PM value on waveshare lcd

### ISSUE THREAD

**Issue by PrzemekSkw** [zefanja/aqi#11]
Hello,
I make pm sensor like in that [tutorial](https://hackernoon.com/how-to-measure-particulate-matter-with-a-raspberry-pi-75faa470ec35) and it works fine. I have connected to my Pi Zero also small waveshare 1.44 lcd [ST7735S] and I want to have that measurements also on that screen. Is it possible? I make that screen works but it's very small and unreadable.
![IMG_20191125_170320245_HDR](https://user-images.githubusercontent.com/25219988/69556986-146e9280-0fa6-11ea-8cbd-2a0e28586d4d.jpg)

Regards,
Przemek

**Comment by zefanja** [comment]
Should be possible, but this is not the scope of this repository. Better ask this on another forum.
