### ISSUE TITLE
Sensor reading interval—optimal time?

### ISSUE THREAD

**Issue by ahabandfedallah** [zefanja/aqi#4]
Using this and loving it. The sensor currently reads for ~30 seconds ever 5 minutes. I've been trying to research what the optimal sensing time is, and some sources say it should be sampling the air constantly. Not sure if I need that for this application (just using it to measure indoor AQI in a future nursery), but does anyone know if there is an optimal interval to take a sensor reading?

**Comment by zefanja** [comment]
At school we run the measurement every 10min for 2min. Depending where you want to use it. You also need to take in account that the sensor has a limited lifetime, so IMHO I won't measure continuously.

**Comment by ghost** [comment]
I've been using a SDS011 for almost 2 years continuously (day and night). Compared to a brand new one last week and readings are within 10%, so still perfectly OK.
I made it a portable raspberry, and I walk in the streets to find pollution peaks, so it has to monitor continuously.

**Comment by zefanja** [comment]
I think there is no optimal internal, it depends really on the use case. If you want constant measurement, than do it. If once in a hour is fine - no need to measure every minute.
